import { CompletedProject, ReportStat } from "../_types/domain";

export const REPORT_CATEGORIES = ["All", "Agriculture", "Poultry", "Dairy", "Fisheries", "Organic Farming"];

export const COMPLETED_PROJECTS: CompletedProject[] = [
    {
        id: "rp-001",
        name: "Aftab Agro Farms",
        category: "Poultry",
        totalRaised: "৳50,00,000",
        investors: 127,
        returnDelivered: "15.2%",
        duration: "12 months",
        completedDate: "December 2024",
        status: "Completed",
        contractType: "Mudarabah",
        description: "Poultry feed processing and distribution expansion project.",
    },
    {
        id: "rp-002",
        name: "Green Valley Rice Mills",
        category: "Agriculture",
        totalRaised: "৳75,00,000",
        investors: 189,
        returnDelivered: "14.8%",
        duration: "9 months",
        completedDate: "November 2024",
        status: "Completed",
        contractType: "Musharakah",
        description: "Rice milling capacity expansion and quality improvement.",
    },
    {
        id: "rp-003",
        name: "Organic Harvest BD",
        category: "Organic Farming",
        totalRaised: "৳35,00,000",
        investors: 94,
        returnDelivered: "16.5%",
        duration: "6 months",
        completedDate: "October 2024",
        status: "Completed",
        contractType: "Murabaha",
        description: "Organic vegetable supply chain and cold storage development.",
    },
    {
        id: "rp-004",
        name: "Fisheries Hub Khulna",
        category: "Fisheries",
        totalRaised: "৳60,00,000",
        investors: 156,
        returnDelivered: "13.9%",
        duration: "12 months",
        completedDate: "September 2024",
        status: "Completed",
        contractType: "Mudarabah",
        description: "Fish processing and export facility modernization.",
    },
    {
        id: "rp-005",
        name: "Dairy Fresh Farms",
        category: "Dairy",
        totalRaised: "৳45,00,000",
        investors: 112,
        returnDelivered: "15.0%",
        duration: "9 months",
        completedDate: "August 2024",
        status: "Completed",
        contractType: "Musharakah",
        description: "Dairy processing plant and distribution network expansion.",
    },
    {
        id: "rp-006",
        name: "Spice Gardens Sylhet",
        category: "Agriculture",
        totalRaised: "৳25,00,000",
        investors: 78,
        returnDelivered: "17.2%",
        duration: "6 months",
        completedDate: "July 2024",
        status: "Completed",
        contractType: "Murabaha",
        description: "Spice cultivation and processing for export market.",
    },
];

export const REPORT_STATS: ReportStat[] = [
    { value: "৳500Cr+", label: "Total Returns Distributed" },
    { value: "25+", label: "Completed Projects" },
    { value: "15.2%", label: "Avg. Return Rate" },
    { value: "100%", label: "On-Time Completion" },
];

export const REPORTS_DATA = [
    {
        id: "1",
        title: "Annual Report 2023",
        category: "annual",
        date: "2024-01-15",
        description: "Comprehensive overview of our platform's performance, growth metrics, and impact in 2023.",
        fileSize: "2.5 MB",
        downloadUrl: "/reports/annual-2023.pdf",
    },
    {
        id: "2",
        title: "Q4 2023 Performance Report",
        category: "quarterly",
        date: "2024-01-05",
        description: "Detailed analysis of Q4 2023 operations, investments, and returns.",
        fileSize: "1.8 MB",
        downloadUrl: "/reports/q4-2023.pdf",
    },
    {
        id: "3",
        title: "Social Impact Report 2023",
        category: "impact",
        date: "2024-02-01",
        description: "Assessment of our platform's social and economic impact on rural communities.",
        fileSize: "3.2 MB",
        downloadUrl: "/reports/impact-2023.pdf",
    },
    {
        id: "4",
        title: "Shariah Audit Report 2023",
        category: "shariah",
        date: "2023-12-20",
        description: "Independent Shariah audit confirming compliance of all transactions and operations.",
        fileSize: "1.5 MB",
        downloadUrl: "/reports/shariah-2023.pdf",
    },
] as const;
